-- RESET VA TABLE FOR A NEW WEEK
UPDATE [VEHICLE ASSIGNMENTS]
SET 
    [BALANCE BROUGHT FORWARD] = Null,
    [RENTAL AMOUNT PAID] = Null,
    [DAMAGES CHARGED] = Null,
    [DAMAGES PAID] = Null,
    [INSURANCE CHARGED] = Null,
    [INSURANCE PAID] = Null,
    [DEPOSIT CHARGED] = Null,
    [DEPOSIT PAID] = Null,
    [TICKET CHARGED] = Null,
    [TICKET PAID] = Null,
    DISCOUNT = Null
WHERE [EndDate] IS NULL;
