-- IMPORT PREVIOUS WEEK BALANCES BACK INTO VA TABLE FOR NEW WEEK
UPDATE 
    [VEHICLE ASSIGNMENTS]
INNER JOIN 
    [WEEKLY PAYMENT LOGS]
ON 
    [VEHICLE ASSIGNMENTS].[ASSIGNMENT ID] = [WEEKLY PAYMENT LOGS].[VA ID]
SET 
    [VEHICLE ASSIGNMENTS].[DAMAGES CHARGED] = [WEEKLY PAYMENT LOGS].[DAMAGESPENDING],
    [VEHICLE ASSIGNMENTS].[TICKET CHARGED] = [WEEKLY PAYMENT LOGS].[TICKETPENDING],
    [VEHICLE ASSIGNMENTS].[DEPOSIT CHARGED] = [WEEKLY PAYMENT LOGS].[DEPOSITPENDING],
    [VEHICLE ASSIGNMENTS].[INSURANCE CHARGED] = [WEEKLY PAYMENT LOGS].[INSURANCEPENDING],
    [VEHICLE ASSIGNMENTS].[BALANCE BROUGHT FORWARD] = [WEEKLY PAYMENT LOGS].[BALANCE CARRIEDFORWARD]
WHERE 
    [WEEKLY PAYMENT LOGS].[WEEK ID] = ([Enter Current Week:] - 1)
    AND [WEEKLY PAYMENT LOGS].[EndDate] IS NULL;
