-- EXPORT FROM VA TABLE INTO WEEKLY PAYMENT LOGS TABLE
PARAMETERS [Enter Week ID:] Long, [Enter Week Start Date:] DateTime;

INSERT INTO [WEEKLY PAYMENT LOGS] 
(
    [VA ID], [WEEK ID], [WEEKLY AMOUNT], [RENTAL AMOUNT PAID], 
    [DAMAGES CHARGED], [DAMAGES PAID], DAMAGESPENDING, 
    [TICKET CHARGED], [TICKET PAID], TICKETPENDING,
    [INSURANCE CHARGED], [INSURANCE PAID], INSURANCEPENDING,
    [DEPOSIT CHARGED], [DEPOSIT PAID], DEPOSITPENDING,
    [BALANCE BROUGHT FORWARD], [BALANCE CARRIEDFORWARD], 
    [TOTAL DUE], DISCOUNT, EndDate
)
SELECT 
    [ASSIGNMENT ID], 
    [Enter Week ID:], 
    [WEEKLY AMOUNT], 
    [RENTAL AMOUNT PAID], 
    [DAMAGES CHARGED], 
    [DAMAGES PAID], 
    [DAMAGESPENDING], 
    [TICKET CHARGED], 
    [TICKET PAID], 
    [TICKETPENDING], 
    [INSURANCE CHARGED], 
    [INSURANCE PAID], 
    [INSURANCEPENDING],
    [DEPOSIT CHARGED], 
    [DEPOSIT PAID], 
    [DEPOSITPENDING],
    [BALANCE BROUGHT FORWARD], 
    [BALANCED CARRIED FORWARD], 
    [TOTAL DUE], 
    [DISCOUNT], 
    [EndDate]
FROM [VEHICLE ASSIGNMENTS]
WHERE EndDate IS NULL 
   OR EndDate >= [Enter Week Start Date];
