-- VEHICLES CURRENTLY AVAILABLE FOR RENTING
SELECT 
    [COMPANY DETAILS].[COMPANY NAME],
    [VEHICLE DETAILS].[VEHICLE REG],
    [DRIVER DETAILS].[DRIVER NAME],
    [VEHICLE DETAILS].[MAKE/MODEL]
FROM 
    [COMPANY DETAILS] 
INNER JOIN 
    ([VEHICLE DETAILS] 
    INNER JOIN (
        [DRIVER DETAILS] 
        INNER JOIN [VEHICLE ASSIGNMENTS] 
            ON [DRIVER DETAILS].[Driver ID] = [VEHICLE ASSIGNMENTS].[DRIVER ID]
    ) 
    ON [VEHICLE DETAILS].[Vehicle ID] = [VEHICLE ASSIGNMENTS].[VEHICLE ID])
ON [COMPANY DETAILS].ID = [VEHICLE DETAILS].[COMPANY ID]
WHERE 
    ([DRIVER DETAILS].[DRIVER NAME] IN ("READY", "ACCIDENT", "PENDING COMPLIANCE", "MECHANIC PROBLEM"))
    AND ([VEHICLE ASSIGNMENTS].EndDate IS NULL);
