-- WEEKLY LOGGED PAYMENTS
SELECT 
    [COMPANY DETAILS].[COMPANY NAME],
    [VEHICLE DETAILS].[VEHICLE REG],
    [VEHICLE ASSIGNMENTS].EndDate,
    [DRIVER DETAILS].[DRIVER NAME],
    [WEEKLY PAYMENT LOGS].[RENTAL AMOUNT PAID],
    RENTAL_WEEKS.[Week Start Date],
    [WEEKLY PAYMENT LOGS].[DEPOSIT CHARGED],
    [WEEKLY PAYMENT LOGS].[DEPOSIT PAID],
    [WEEKLY PAYMENT LOGS].DISCOUNT,
    [WEEKLY PAYMENT LOGS].[BALANCE CARRIEDFORWARD],
    [WEEKLY PAYMENT LOGS].[WEEKLY AMOUNT],
    [WEEKLY PAYMENT LOGS].[BALANCE BROUGHT FORWARD],
    [WEEKLY PAYMENT LOGS].[TICKET CHARGED],
    [WEEKLY PAYMENT LOGS].[TICKET PAID],
    [WEEKLY PAYMENT LOGS].[INSURANCE CHARGED],
    [WEEKLY PAYMENT LOGS].[INSURANCE PAID],
    [WEEKLY PAYMENT LOGS].[DAMAGES CHARGED],
    [WEEKLY PAYMENT LOGS].DAMAGESPENDING,
    [VEHICLE ASSIGNMENTS].[DATE ASSIGNED],
    [WEEKLY PAYMENT LOGS].[DAMAGES PAID],
    [WEEKLY PAYMENT LOGS].INSURANCEPENDING,
    [WEEKLY PAYMENT LOGS].TICKETPENDING,
    [WEEKLY PAYMENT LOGS].DEPOSITPENDING
FROM RENTAL_WEEKS 
INNER JOIN (
    [DRIVER DETAILS] 
    INNER JOIN (
        ([COMPANY DETAILS] 
            INNER JOIN [VEHICLE DETAILS] 
                ON [COMPANY DETAILS].ID = [VEHICLE DETAILS].[COMPANY ID]
        )
        INNER JOIN [VEHICLE ASSIGNMENTS] 
            ON [VEHICLE DETAILS].[Vehicle ID] = [VEHICLE ASSIGNMENTS].[VEHICLE ID]
        ON [DRIVER DETAILS].[Driver ID] = [VEHICLE ASSIGNMENTS].[DRIVER ID]
    )
    INNER JOIN [WEEKLY PAYMENT LOGS] 
        ON [VEHICLE ASSIGNMENTS].[ASSIGNMENT ID] = [WEEKLY PAYMENT LOGS].[VA ID]
)
ON RENTAL_WEEKS.WEEKID = [WEEKLY PAYMENT LOGS].[WEEK ID];
